### ISSUE TITLE
Serious question

### ISSUE THREAD

**Issue by Ekultek** [NationalSecurityAgency/lemongraph#2]
Who's bright idea was it to get you guys a github?

**Comment by ctubbsii** [comment]
@Ekultek This issue forum is for bug tracking, feature requests, usability questions, and other issues pertaining to the development of the open source code in this repository. You can direct other questions to [this contact form][1]. Please keep the GitHub issues forum useful by staying on topic when participating here. Thank you for your consideration.

[1]: https://www.nsa.gov/about/contact-us/

**Comment by Ekultek** [comment]
Lol that answers that question. So lemme see if I've got this straight, you get a bunch of hacking and exploits dumped, on github, then out of nowhere make a github, then you expect open source developers to feel comfortable enough to send pull requests and issues to your development? Riddle me this if you would kind sir, what if I do contribute to you, and you accept my pull request, how am I to know that you won't use what I know against some innocent civilian for _national security_ precautions?

**Comment by ctubbsii** [comment]
@Ekultek Once again, this is not the appropriate venue for your questions and concerns. I appreciate you wish to express your views, but this is not on topic for this code repository. Please see my previous response for a more appropriate venue for contacting somebody who can answer your questions.

This thread will now be locked, since an appropriate response to the inquiry has been provided.
